export default defineAppConfig({
  pages: [
    "pages/demo/index",
    "pages/index/index",
    "pages/groups/index",
    "pages/publish/index",
    "pages/roulette/index",
    "pages/profile/index",
    "pages/login/index",
    "pages/detail/index",
    "pages/group-detail/index",
    "pages/notifications/index",
    "pages/favorites/index",
    "pages/favorites-import/index",
    "pages/favorite-edit/index",
    "pages/poster/index",
    "pages/webview/index",
  ],
  tabBar: {
    custom: true,
    color: "#9ca3af",
    selectedColor: "#ff6b35",
    backgroundColor: "#ffffff",
    borderStyle: "white",
    list: [
      { pagePath: "pages/index/index", text: "动态" },
      { pagePath: "pages/groups/index", text: "圈子" },
      { pagePath: "pages/publish/index", text: "发布" },
      { pagePath: "pages/roulette/index", text: "转盘" },
      { pagePath: "pages/profile/index", text: "我的" },
    ],
  },
  window: {
    backgroundTextStyle: "light",
    navigationBarBackgroundColor: "#ffffff",
    navigationBarTitleText: "飨刻",
    navigationBarTextStyle: "black",
  },
});
